# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 833f016c952d405582d9964bd28f1332a370aef1f2d9a66d5b14a5e7bde564fd4a705d1034d8f1e3bdb1dab636644bb4fa3bc14da963974e81569fc06c0b4166

test:
  secret_key_base: e4ae1b452530fe680c6130abb12bdec6ace27b953c0dab0afdff5564204e8df64152ca13b5bb72fd2f728f04fc49a38e629fc2bffeed2fd7f312a28affee6d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
